name: thesis_python
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.16=h3f729d1_0
  - pip=25.1=pyhc872135_2
  - python=3.11.11=h4607a30_0
  - setuptools=78.1.1=py311haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h0416ee5_0
  - vc=14.42=haa95532_5
  - vs2015_runtime=14.42.34433=hbfb602d_5
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - asttokens==3.0.0
      - attrs==25.3.0
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - et-xmlfile==2.0.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fonttools==4.58.0
      - ipykernel==6.29.5
      - ipython==9.2.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.8
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - narwhals==1.40.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpy==2.2.6
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.2.3
      - parso==0.8.4
      - pillow==11.2.1
      - platformdirs==4.3.8
      - plotly==6.1.0
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywin32==310
      - pyzmq==26.4.0
      - qutip==5.1.1
      - referencing==0.36.2
      - rpds-py==0.25.0
      - scipy==1.15.3
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tornado==6.5
      - traitlets==5.14.3
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - wcwidth==0.2.13
prefix: C:\Users\znurs\anaconda3\envs\thesis_python
